<!DOCTYPE html>
<html lang="ru">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="/styles/style.css">
  <title>PHP CRUD API</title>
</head>

<body class="bg-green">
  <p>POST / - CREATE</p>
  <pre>
  BODY - JSON {
                  "title": title,
                  "author": author,
                  "published_at": year
              }
  </pre>
  <p>GET / - READ</p>
  No BODY needed 
  <p>PUT / - UPDATE</p>
  <pre>
  BODY - JSON {
                  "id": id,
                  "title": title,
                  "author": author,
                  "published_at": year
              }
  </pre>
  <p>DELETE / - DELETE</p>
  <pre>
  BODY - JSON {
                  "id": id
              }
  </pre>
</body>

</html>