version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-php-crud-api
    container_name: php-crud-api
    ports:
      - "9090:80"
    volumes:
      - .:/var/www/html
      - apache_logs:/var/log/apache2
    environment:
      - DATABASE_URL=${DATABASE_URL}
    depends_on:
      - db

  db:
    image: mysql:8.0
    container_name: mysql-db
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
  apache_logs: