version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: my-php-crud-api
    container_name: php-crud-api
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    depends_on:
      - db

  db:
    image: mysql:8.0.36
    container_name: mysql-db
    environment:
      - MYSQL_ROOT_PASSWORD=your_root_password
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=your_user
      - MYSQL_PASSWORD=your_password
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: