CREATE TABLE IF NOT EXISTS users (
    id MEDIUMINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    login VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    hashed_token VARCHAR(255) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS books (
    id MEDIUMINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    title VARCHAR(1024) NOT NULL,
    author VARCHAR(255) NOT NULL,
    published_at SMALLINT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS opinions (
    id MEDIUMINT NOT NULL PRIMARY KEY AUTO_INCREMENT,
    author_login VARCHAR(255) NOT NULL,
    book_id MEDIUMINT NOT NULL,
    opinion TEXT NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (book_id) REFERENCES books(id) ON DELETE CASCADE
);