name: ftp-deploy

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - name: Get latest code
      uses: actions/checkout@v3

    - name: FTP Deploy Dir 1
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp-php-crud-api.alwaysdata.net
        username: php-crud-api
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        log-level: minimal
        server-dir: /App/
        local-dir: project/App/

    - name: FTP Deploy Dir 2
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ftp-php-crud-api.alwaysdata.net
        username: php-crud-api
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftps
        log-level: minimal
        server-dir: /www/
        local-dir: project/public/